################################# Default configuration ###################
baseURL = "http://examplesite.org"
title = "A Operat .pl"
theme = "airspace-hugo"
#themesDir = "../.."
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
defaultContentLanguage = "pl"

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "150px"
# Meta data
description = "Wycena nieruchomości"
author = "aoperat.pl"
# Contact Information
mobile = "0124857985320"
email = "kontakt [małpa] aoperat.pl"
location = "kraków 31-414, ul. Celarowska 18"
# contact form action
contact_form_action = "https://formspree.io/myykjpje" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "G-V71K9QBHRC" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ Polish Language ########################
[Languages.pl]
languageName = "Pl"
languageCode = "pl-pl"
contentDir = "content/polish"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 aoperat.pl Wszelkie prawa zastzerzone"


######################### polish navigation #############################
# main menu
[[Languages.pl.menu.main]]
name = "O Nas"
URL = "about"
weight = 1


[[Languages.pl.menu.main]]
name = "O Platformie"
URL = "platform"
weight = 2

[[Languages.pl.menu.main]]
name = "Wyceń nieruchomość"
URL = "https://forms.gle/hWLpbgDHWYJrHk9H8"
weight = 3

[[Languages.pl.menu.main]]
name = "Panel rzeczoznawcy"
URL = "panel"
weight = 4

[[Languages.pl.menu.main]]
name = "Blog"
URL = "blog"
weight = 5


[[Languages.pl.menu.main]]
name = "Kontakt"
URL = "contact"
weight = 6



# footer menu
[[Languages.pl.menu.footer]]
name = "O Nas"
URL = "about"
weight = 1

[[Languages.pl.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[Languages.pl.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[Languages.pl.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[Languages.pl.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.pl.menu.footer]]
name = "Kontakt"
URL = "contact"
weight = 6